import { useAuthPage } from '@cc/shared/lib';
import { RoutesTypes } from '@cc/shared/types';
import { InvestmentCardsList } from '@cc/widgets';
import Head from 'next/head';

export default function InvestmentCards() {
  const { showContent } = useAuthPage({ redirectTo: RoutesTypes.MAIN });

  return (
    <>
      <Head>
        <title>Calculator | Investment cards list</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      {showContent && <InvestmentCardsList />}
    </>
  );
}
