import { useNotAuthPage } from '@cc/shared/lib';
import { RoutesTypes } from '@cc/shared/types';
import { LoginForm } from '@cc/widgets';
import Head from 'next/head';

export default function Login() {
  const { showContent } = useNotAuthPage({ redirectTo: RoutesTypes.MAIN });

  return (
    <>
      <Head>
        <title>Calculator | Log in</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      {showContent && <LoginForm />}
    </>
  );
}
