import { PageLayout } from '@cc/app/components';
import { RoutesTypes } from '@cc/shared/enums';
import { useAuthPage } from '@cc/shared/lib';
import { CalculateYieldForm } from '@cc/widgets';
import Head from 'next/head';

export default function CalculateYield() {
  useAuthPage({ redirectTo: RoutesTypes.MAIN });

  return (
    <PageLayout centerContent>
      <Head>
        <title>Calculate monthly yield | Crypto Metrics</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
      </Head>

      <CalculateYieldForm />
    </PageLayout>
  );
}
