import { AuthPage, PageLayout } from '@cc/app/components';
import { CalculateYieldForm } from '@cc/widgets';
import Head from 'next/head';

export default function CalculateYield() {
  return (
    <AuthPage>
      <PageLayout centerContent>
        <Head>
          <title>Calculate monthly yield | Crypto Metrics</title>
          <meta name="description" content="Generated by create next app" />
          <meta name="viewport" content="width=device-width, initial-scale=1" />
        </Head>

        <CalculateYieldForm />
      </PageLayout>
    </AuthPage>
  );
}
