import { NotAuthPage, PageLayout } from '@cc/app/components';
import { LoginForm } from '@cc/widgets';
import { NextPage } from 'next';
import Head from 'next/head';

const Login: NextPage = () => {
  return (
    <NotAuthPage>
      <PageLayout centerContent>
        <Head>
          <title>Log in | Crypto Metrics</title>
          <meta name="description" content="Generated by create next app" />
          <meta name="viewport" content="width=device-width, initial-scale=1" />
        </Head>

        <LoginForm />
      </PageLayout>
    </NotAuthPage>
  );
};

export default Login;
