import { PageLayout } from '@cc/app/components';
import { RoutesTypes } from '@cc/shared/enums';
import { useNotAuthPage } from '@cc/shared/lib';
import { SignUpForm } from '@cc/widgets';
import Head from 'next/head';

export default function SignUp() {
  // const { showContent } = useNotAuthPage({ redirectTo: RoutesTypes.MAIN });

  return (
    <PageLayout centerContent>
      <Head>
        <title>Calculator | Sign up</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <SignUpForm />
    </PageLayout>
  );
}
