import { DetailedInvestmentStatistics, GeneralInvestmentStatistics } from '@cc/features';
import { useAuthPage } from '@cc/shared/lib';
import { RoutesTypes } from '@cc/shared/types';
import { Box, Container } from '@mui/material';
import Head from 'next/head';

export default function InvestmentStatistics() {
  const { showContent } = useAuthPage({ redirectTo: RoutesTypes.MAIN });

  return (
    <>
      <Head>
        <title>Calculator | Investment cards list</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      {showContent && (
        <Container maxWidth="sm">
          <Box mb={3}>
            <GeneralInvestmentStatistics />
          </Box>

          <DetailedInvestmentStatistics />
        </Container>
      )}
    </>
  );
}
