import { PageLayout } from '@cc/app/components';
import { Container, Typography } from '@mui/material';
import Head from 'next/head';
import globalStyles from '@cc/shared/styles/Index.module.css';

export default function Custom404() {
  return (
    <PageLayout centerContent>
      <Head>
        <title>Calculator | 404 Not Found</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Container maxWidth="xs" className={globalStyles.opacityContainer}>
        <Typography variant="h5" component="h1" fontWeight="600" textAlign="center">
          404 - Page Not Found
        </Typography>
      </Container>
    </PageLayout>
  );
}
