import { RoutesTypes } from '@cc/shared/enums';
import { useNotAuthPage } from '@cc/shared/lib';
import Head from 'next/head';

export default function Home() {
  // useNotAuthPage({ redirectTo: RoutesTypes.CALCULATE_YIELD });

  return (
    <>
      <Head>
        <title>Crypto Financial Calculator</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
    </>
  );
}
