import { PageLayout } from '@cc/app/components';
import { MainContent } from '@cc/widgets';
import Head from 'next/head';

export default function Home() {
  return (
    <PageLayout>
      <Head>
        <title>Calculator | Main</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <MainContent />
    </PageLayout>
  );
}
